### ISSUE TITLE
text editor format appending double quotes conflict with json structure

### ISSUE THREAD

**Issue by EFXPROMedia** [webfashionist/RichText#1]
I am loving this Wysiwigg the down of it is that for some reason it's not escaping double quotes correctly and conflicting on the json structure causing it to duplicate the line previously saved.

If you look at my example the text duplicated, if I go on code view and replace double quotes for single quotes it fixes all and saves again without duplicating the content.

https://www.dropbox.com/s/qgsxjg8pf0999q0/Screenshot%202017-07-28%2010.27.17.png?dl=0

https://www.dropbox.com/s/vm0nc6ft66tw217/Screenshot%202017-07-28%2010.27.04.png?dl=0

THE JSON:

`{"above_price":"48Hrs</font></b> delivery service with SMS or email notification! because your order is cartPriceTotal**\">**You got UK free track <b><font color=\"#000000\">48Hrs</font></b> delivery service with SMS or email notification! because your order is cartPriceTotal"}`

**Comment by webfashionist** [comment]
Thank you for your feedback.

However, I suppose your issue comes from whatever backend code you are using. 
I've copied your JSON to the editor, saved it and loaded the saved page with the new content and everything was fine.

If the code is fine before saving (and even the code view - with the black background - looks OK), then the bug does not occur within the WYSIWYG.

**Comment by EFXPROMedia** [comment]
My application rendering is liquid, but in the json I sent you the quote is encoded and not escaped, so if I send the HTML entered in the editor using single quotes would fix it can you suggest me where I could change it to output single quotes only so instead of inline css going style="" to style='' ?

**Comment by webfashionist** [comment]
Depends on what kind of styling should get single quotes instead of double quotes, as most of the things are directly generated by the browser and the `contenteditable` attribute. 

There are however a few quotes you can change by editing the JavaScript file (you will then have to minify it again if you need the minified file).

What I probably would recommend you in your case, is that you write a function which replaces double quotes by single quotes wherever needed for the textarea field and the div container which contains the HTML code of your content. 

I can't tell yet if I will implement this as a feature anytime soon, as this is a quite specific issue which doesn't occur on a daily basis with CMS tools for example.

**Comment by EFXPROMedia** [comment]
Editing the javascript and minifying it wouldn't be a problem I use CodeKit to compile the code minified, the problem is that the editor automatically adds the double quotes as the user writes the content and adding styles so essentially I would like to add the single quotes functionality directly into the main script of your plugin.

Can you give me some directions where I can change the code being generated to replace the double quotes to single ones? I am using chrome, Safari and firefox to test it.

At some point as well I noticed that when you are writing the content the actual textarea it does not clear the current content in order to update it with the new writing coming from the container .richText-editor

this **">** keeps being generated after any style applied to the text and saved but it is added encoded as **&nbsp;"&gt;** .

The content is saved by JSON.stringify([object]);  that if I use it with a plain textarea I have no problem.

Sorry I am not trying to create problems where you maybe don't see it but I like your app and I could help contributing on fixing it so it becomes the best!

**Comment by webfashionist** [comment]
Okay so did I understand you correctly?
You aren't writing the JSON object directly in the editor, but one of the values of the object is written to the editor and saved back to the JSON object?

So, when taking your example, you only have the following content inside the editor:

```48Hrs</font></b> delivery service with SMS or email notification! because your order is cartPriceTotal**\">**You got UK free track <b><font color=\"#000000\">48Hrs</font></b> delivery service with SMS or email notification! because your order is cartPriceTotal```

And if you save it, it simply returns the content to your JSON object?
So to solve it, every single double quote should be replaced by a single quote?

**Comment by EFXPROMedia** [comment]
Yes, I think you understand it now, basically because I'm using liquid I get the form content to JSON then I render it back in the textarea so the user can see what was entered previously so they can edit it, after edited and saved it duplicates but it duplicates because somehow the double quotes were red from the liquid entered in the textarea.

So yes, Single quotes would fix the problem I think because in liquid double quotes are treated as the object separetion and should be accompanied by a comma "," before the next object. If I re-format the content using single quotes on the code view it saves properly

**Comment by webfashionist** [comment]
I've updated the code to add a new setting/option `useSingleQuotes` (444dc34).
In your case you should set it to `true` when initializing the editor, e.g.:

`$('textarea').richText({useSingleQuotes: true});`

Please keep me up-to-date if it works for you.

**Comment by EFXPROMedia** [comment]
Hi, thanks for the update but I am still getting the quotes:

https://www.dropbox.com/s/n86ctny76t8kgux/Screenshot%202017-07-31%2010.18.15.png?dl=0

I also tested your plug in on Safari and Firefox and it completely doesn't work on them.

**Comment by webfashionist** [comment]
Have you initialized the editor with `{useSingleQuotes: true}` ?
What have you done? So that I'm able to reproduce it.

The way I've tested it:

**Option 1**
1. I input content in the editor
2. The content is directly written with single quotes in the `textarea`

--

**Option 2**
1. I write HTML code with attributes in the editor (code-side)
2. With the latest update I've just uploaded, the quotes around the attribute get immediately replaced.

--

**Option 3**
1. Adding code elements through the toolbar
2. Directly pastes it with single quotes in the `textarea` as well.


All the above ways have worked fine for me.

**Comment by EFXPROMedia** [comment]
Apparently all editors work the same and I believe it should be working just fine now, I finally found that the problem is the liquid code I used so for best server side code best fetching all content via ajax and update it every time a change is made to at the form just in case the data doesn't get lost on submitting, liquid will output the texture input as is with double quotes.
