### ISSUE TITLE
Do you have a "Font-size"?

### ISSUE THREAD

**Issue by IgnacioGans** [webfashionist/RichText#17]
Hi, i don't see in **RichText**  "Font-size". 
Do you have this in somewhere in the code? 

![image](https://user-images.githubusercontent.com/3810688/37287975-78890350-25dc-11e8-9420-751bfffe2d11.png)

**Comment by webfashionist** [comment]
Hi,

Currently this is only implemented through the heading (h1-h6) options and not through the `font-size` option as you described it.

It is going to be implemented as soon as possible

**Comment by IgnacioGans** [comment]
Awesome, good luck!

**Comment by webfashionist** [comment]
I've added a new toolbar button for the font sizes ( b37cf82 ).
Currently only predefined sizes (24,18,16,14,12 pixels) are available.

A known issue is, that line breaks sometimes get removed depending on where the font size will be set.
Until that issue is fixed, you can clone or download the latest version from the [main repository page](https://github.com/webfashionist/RichText).


PS: Further updates have since been released as well, which are already available in a [new version](https://github.com/webfashionist/RichText/releases) :-)

**Comment by IgnacioGans** [comment]
Awesome! Having great day!
