### ISSUE TITLE
replace <b> and <i> tags by <strong> and <em>

### ISSUE THREAD

**Issue by iorien** [webfashionist/RichText#19]
Hi, Is it possible to replace the `<b>`, `<i>` and `<u>` tags for `<strong>`, `<em>` or even `<span class="underlined">`? How? Thank you

**Comment by webfashionist** [comment]
It would be possible with a few more code changes. Currently it uses the default setting from the browsers (as it is based on a browser-specific API).

The reason for using `<b>` instead of `<strong>`, same as `<i>` instead of `<em>` is described quite well in this StackOverflow post: [What's the difference between `<b>` and `<strong>`, `<i>` and `<em>`?
](https://stackoverflow.com/questions/271743/whats-the-difference-between-b-and-strong-i-and-em#271776)

Therefore, changing it within the RichText editor itself would probably not make sense, as these tags do have different meanings (even if the visual result is the same). 

If however, you are aware of the difference of both "categories" of tags, I'll consider to add them through an optional setting. 
If you still want to have the other tags, without caring about their difference, you probably should process/replace the existing tags just before saving the HTML content to your database.

**Comment by iorien** [comment]
thank you, I finally chose to replace the text before inserting it. I was just curious to know if there was a quick method already created to replace the tags.
