### ISSUE TITLE
Using RichText as a TinyMCE replacement in WordPress

### ISSUE THREAD

**Issue by cocodedesigns** [webfashionist/RichText#5]
I'm not sure if this is an issue that can be fixed easily, but I'm looking for a replacement for TinyMCE in my WordPress widget (TinyMCE is causing too many issues that I've given up trying to fix), and so far RichText has proven an editor I really like.  However, I've noticed that when I create my text, each paragraph is written into a new `<div>` as opposed to a `<p>`, which I know TinyMCE defaults to.  But once a paragraph has been hardcoded in (or inserted in via default text), each subsequent paragraph seems to follow suit; it's just when the field is empty that it reverts back to not using paragraph tags. Is there a way to do that in the editor from the first paragraph, so that they are all using `<p>`s instead of `<div>`s?

**Comment by webfashionist** [comment]
Thank you for your feedback! I'm glad you like RichText.

I've added a new option called `useParagraph`, set it to `(boolean) true` and paragraphs will be used instead of div containers. div containers is the default setting by the browsers, that's the reason why it may differ from other editors and as well the reason why I'd keep it as default for the editor as well.

Please keep me up-to-date if you encounter further issues.

---

*This update is not yet in the [releases](https://github.com/webfashionist/RichText/releases) list, if you need to download it, please do so by downloading it using the `Clone or download` button on the repository page.*

If you want to know more about the available options and their default values, please see the [README](https://github.com/webfashionist/RichText#options) file.

**Comment by cocodedesigns** [comment]
That is perfect, and it's working almost like a charm.  It doesn't wrap the first line in a paragraph, only from the second line onwards, which may be something to look into, but apart from that works brilliantly. Thank you for that info.

**Comment by webfashionist** [comment]
You are right, this is now fixed. 
The first line is now wrapped in either `<p>` or `<div>` tags depending on your options.

I've as well added that last fix to the latest release.
